server:
  port: 8080

spring:
  application:
    name: lotto
  profiles:
    active: local
  datasource:    
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localvmdb.mariadb_11:33306/lotto
    username: lottouser
    password: lottouser
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: GuestbookHikariCP
  jpa:
    hibernate:
      ddl-auto: update      
    show-sql: true
    open-in-view: false
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.dialect]": org.hibernate.dialect.MariaDBDialect
      # ğŸ’¡ìŠ¤í”„ë§ 3.3.xì—ì„œëŠ” ì •ì˜í•  í•„ìš”ì—†ë‹¤ê³  ê²½ê³  ë¡œê·¸ê°€ ë‚˜ì˜¤ì§€ë§Œ, 
      #    ì˜¤ë¥˜ ìƒí™©ì— ìˆì„ ë•ŒëŠ” Dialectë¥¼ ì§€ì •í•´ì•¼ ì˜¤ë¥˜ë¡œê·¸ê°€ ì •í™•í•˜ê²Œ ë‚˜ì˜¨ë‹¤.
      #    ìŠ¤í„°ë”” ëª©ì  í”„ë¡œì íŠ¸ì—ì„œëŠ” í•­ìƒ ì„¤ì •í•´ë‘ëŠ” ê²ƒì´ ì¢‹ê² ë‹¤.

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} [%thread] %clr(%-5level) %clr(%logger{72}){cyan} - %msg%n"
  level:
    root: info
    web: debug
    "[org.fp024.lotto]": debug
    "[org.hibernate.orm.jdbc.bind]": trace
    # "[org.hibernate.orm.jdbc.extract]": trace

---
spring:
  config:
    activate:
      on-profile:
      - local      
  devtools:
    # ğŸ’¡ìë™ìœ¼ë¡œ ë‹¤ìŒì— ëª…ì‹œëœ í”„ë¡œí¼í‹°ë¥¼ ì¶”ê°€í•˜ëŠ”ë°, ë‚˜ëŠ” í•„ìš”í•œ ê²ƒë§Œ ëª…ì‹œì ìœ¼ë¡œ ë„£ëŠ” ê²ƒì´ ì¢‹ê² ë‹¤.
    # https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-devtools/src/main/resources/org/springframework/boot/devtools/env/devtools-property-defaults.properties
    add-properties: false
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
      chain:
        cache: false

---
spring:
  config:
    activate:
      on-profile:
      - prod
